name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Check out el código
    - name: Check out repository
      uses: actions/checkout@v4

    # Paso 2: Desplegar a Firebase Hosting usando la acción oficial
    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
        channelId: live
